//Generated by ClassMapGenerator.py
//Classmap.h defines ARMCastLookupTable
//Because ARM_CAST macro doesn't work with templates, we need a way to get from a class name to the ARMCastTo.. for it.
//This is accomplished by doing a lookup in the map of the name of the class, whose value will be a function pointer to the proper ARMCastTo... function.
//
//Composed by Samson
//
//6/27/2014

#include <map>
#include <string>
#include <ARM.h>
#pragma once

//Fill a table with all the ARM classes and a function pointer to their ARMCastTo... function.
typedef void*(*ARMCastPtr)(ARMObject*);
const ARMCastPtr ARMCastLookupTable(std::string name)
{
	if("DRAUGHTING_CALLOUT_ITEM_IF"==name) return &ARMCastToDraughting_callout_item_IF;
	if("TARGET_RECTANGLE_IF"==name) return &ARMCastToTarget_rectangle_IF;
	if("SIZE_DIMENSION_IF"==name) return &ARMCastToSize_dimension_IF;
	if("PARALLELISM_TOLERANCE_IF"==name) return &ARMCastToParallelism_tolerance_IF;
	if("TARGET_STRAIGHT_LINE_IF"==name) return &ARMCastToTarget_straight_line_IF;
	if("STYLED_SHADED_MODEL_IF"==name) return &ARMCastToStyled_shaded_model_IF;
	if("TOLERANCE_PLUS_MINUS_VALUE_IF"==name) return &ARMCastToTolerance_plus_minus_value_IF;
	if("DATUM_TARGET_IF"==name) return &ARMCastToDatum_target_IF;
	if("POSITION_TOLERANCE_IF"==name) return &ARMCastToPosition_tolerance_IF;
	if("TARGET_AREA_IF"==name) return &ARMCastToTarget_area_IF;
	if("CIRCULAR_RUNOUT_TOLERANCE_IF"==name) return &ARMCastToCircular_runout_tolerance_IF;
	if("WIDTH_SIZE_DIMENSION_IF"==name) return &ARMCastToWidth_size_dimension_IF;
	if("WORKPIECE_ASSEMBLY_COMPONENT_IF"==name) return &ARMCastToWorkpiece_assembly_component_IF;
	if("CYLINDRICITY_TOLERANCE_IF"==name) return &ARMCastToCylindricity_tolerance_IF;
	if("COMPOSITE_CALLOUT_IF"==name) return &ARMCastToComposite_callout_IF;
	if("LENGTH_SIZE_DIMENSION_IF"==name) return &ARMCastToLength_size_dimension_IF;
	if("PROPERTY_IF"==name) return &ARMCastToProperty_IF;
	if("CONCENTRICITY_TOLERANCE_IF"==name) return &ARMCastToConcentricity_tolerance_IF;
	if("DERIVED_GEOMETRY_IF"==name) return &ARMCastToDerived_geometry_IF;
	if("SINGLE_DATUM_IF"==name) return &ARMCastToSingle_datum_IF;
	if("FLATNESS_TOLERANCE_IF"==name) return &ARMCastToFlatness_tolerance_IF;
	if("GEOMETRIC_CONTEXT_IF"==name) return &ARMCastToGeometric_context_IF;
	if("STYLED_GEOMETRIC_MODEL_IF"==name) return &ARMCastToStyled_geometric_model_IF;
	if("WORKPIECE_IF"==name) return &ARMCastToWorkpiece_IF;
	if("DATUM_DEFINED_BY_TARGETS_IF"==name) return &ARMCastToDatum_defined_by_targets_IF;
	if("COAXIALITY_TOLERANCE_IF"==name) return &ARMCastToCoaxiality_tolerance_IF;
	if("LINE_PROFILE_TOLERANCE_IF"==name) return &ARMCastToLine_profile_tolerance_IF;
	if("ANGULAR_SIZE_DIMENSION_IF"==name) return &ARMCastToAngular_size_dimension_IF;
	if("LINEAR_DISTANCE_DIMENSION_IF"==name) return &ARMCastToLinear_distance_dimension_IF;
	if("STYLED_DRAUGHTING_MODEL_IF"==name) return &ARMCastToStyled_draughting_model_IF;
	if("DATUM_IF"==name) return &ARMCastToDatum_IF;
	if("SINGLE_STYLED_ITEM_IF"==name) return &ARMCastToSingle_styled_item_IF;
	if("LOCATION_DIMENSION_IF"==name) return &ARMCastToLocation_dimension_IF;
	if("DATUM_DEFINED_BY_DERIVED_SHAPE_IF"==name) return &ARMCastToDatum_defined_by_derived_shape_IF;
	if("GEOMETRIC_TOLERANCE_IF"==name) return &ARMCastToGeometric_tolerance_IF;
	if("TARGET_POINT_IF"==name) return &ARMCastToTarget_point_IF;
	if("DATUM_DEFINED_BY_FEATURE_IF"==name) return &ARMCastToDatum_defined_by_feature_IF;
	if("GEOMETRIC_DIMENSION_IF"==name) return &ARMCastToGeometric_dimension_IF;
	if("DIAMETER_SIZE_DIMENSION_IF"==name) return &ARMCastToDiameter_size_dimension_IF;
	if("ANGULAR_LOCATION_DIMENSION_IF"==name) return &ARMCastToAngular_location_dimension_IF;
	if("TOLERANCE_ZONE_IF"==name) return &ARMCastToTolerance_zone_IF;
	if("HEIGHT_SIZE_DIMENSION_IF"==name) return &ARMCastToHeight_size_dimension_IF;
	if("CALLOUT_IF"==name) return &ARMCastToCallout_IF;
	if("CURVED_SIZE_DIMENSION_IF"==name) return &ARMCastToCurved_size_dimension_IF;
	if("DIRECTED_ANGULAR_LOCATION_DIMENSION_IF"==name) return &ARMCastToDirected_angular_location_dimension_IF;
	if("TOTAL_RUNOUT_TOLERANCE_IF"==name) return &ARMCastToTotal_runout_tolerance_IF;
	if("PLUS_MINUS_VALUE_IF"==name) return &ARMCastToPlus_minus_value_IF;
	if("ROUNDNESS_TOLERANCE_IF"==name) return &ARMCastToRoundness_tolerance_IF;
	if("PLACED_TARGET_IF"==name) return &ARMCastToPlaced_target_IF;
	if("THICKNESS_SIZE_DIMENSION_IF"==name) return &ARMCastToThickness_size_dimension_IF;
	if("STRAIGHTNESS_TOLERANCE_IF"==name) return &ARMCastToStraightness_tolerance_IF;
	if("STYLED_MODEL_IF"==name) return &ARMCastToStyled_model_IF;
	if("DATUM_REFERENCE_IF"==name) return &ARMCastToDatum_reference_IF;
	if("CURVED_DISTANCE_DIMENSION_IF"==name) return &ARMCastToCurved_distance_dimension_IF;
	if("TARGET_CIRCLE_IF"==name) return &ARMCastToTarget_circle_IF;
	if("ANGULARITY_TOLERANCE_IF"==name) return &ARMCastToAngularity_tolerance_IF;
	if("RADIAL_SIZE_DIMENSION_IF"==name) return &ARMCastToRadial_size_dimension_IF;
	if("DIRECTED_CURVED_DISTANCE_DIMENSION_IF"==name) return &ARMCastToDirected_curved_distance_dimension_IF;
	if("PERPENDICULARITY_TOLERANCE_IF"==name) return &ARMCastToPerpendicularity_tolerance_IF;
	if("DIRECTED_LINEAR_DISTANCE_DIMENSION_IF"==name) return &ARMCastToDirected_linear_distance_dimension_IF;
	if("SYMMETRY_TOLERANCE_IF"==name) return &ARMCastToSymmetry_tolerance_IF;
	if("SURFACE_PROFILE_TOLERANCE_IF"==name) return &ARMCastToSurface_profile_tolerance_IF;
	if("WORKPIECE"==name) return &ARMCastToWorkpiece;
	if("WORKPIECE_ASSEMBLY_COMPONENT"==name) return &ARMCastToWorkpiece_assembly_component;
	if("DIRECTED_ANGULAR_LOCATION_DIMENSION"==name) return &ARMCastToDirected_angular_location_dimension;
	if("ANGULAR_LOCATION_DIMENSION"==name) return &ARMCastToAngular_location_dimension;
	if("ANGULAR_SIZE_DIMENSION"==name) return &ARMCastToAngular_size_dimension;
	if("ANGULARITY_TOLERANCE"==name) return &ARMCastToAngularity_tolerance;
	if("CIRCULAR_RUNOUT_TOLERANCE"==name) return &ARMCastToCircular_runout_tolerance;
	if("COAXIALITY_TOLERANCE"==name) return &ARMCastToCoaxiality_tolerance;
	if("CONCENTRICITY_TOLERANCE"==name) return &ARMCastToConcentricity_tolerance;
	if("DIRECTED_CURVED_DISTANCE_DIMENSION"==name) return &ARMCastToDirected_curved_distance_dimension;
	if("CURVED_DISTANCE_DIMENSION"==name) return &ARMCastToCurved_distance_dimension;
	if("CURVED_SIZE_DIMENSION"==name) return &ARMCastToCurved_size_dimension;
	if("CYLINDRICITY_TOLERANCE"==name) return &ARMCastToCylindricity_tolerance;
	if("DATUM_DEFINED_BY_DERIVED_SHAPE"==name) return &ARMCastToDatum_defined_by_derived_shape;
	if("DATUM_DEFINED_BY_FEATURE"==name) return &ARMCastToDatum_defined_by_feature;
	if("DATUM_DEFINED_BY_TARGETS"==name) return &ARMCastToDatum_defined_by_targets;
	if("DATUM_REFERENCE"==name) return &ARMCastToDatum_reference;
	if("DIAMETER_SIZE_DIMENSION"==name) return &ARMCastToDiameter_size_dimension;
	if("FLATNESS_TOLERANCE"==name) return &ARMCastToFlatness_tolerance;
	if("GEOMETRIC_CONTEXT"==name) return &ARMCastToGeometric_context;
	if("HEIGHT_SIZE_DIMENSION"==name) return &ARMCastToHeight_size_dimension;
	if("LENGTH_SIZE_DIMENSION"==name) return &ARMCastToLength_size_dimension;
	if("DIRECTED_LINEAR_DISTANCE_DIMENSION"==name) return &ARMCastToDirected_linear_distance_dimension;
	if("LINEAR_DISTANCE_DIMENSION"==name) return &ARMCastToLinear_distance_dimension;
	if("LINE_PROFILE_TOLERANCE"==name) return &ARMCastToLine_profile_tolerance;
	if("PARALLELISM_TOLERANCE"==name) return &ARMCastToParallelism_tolerance;
	if("PERPENDICULARITY_TOLERANCE"==name) return &ARMCastToPerpendicularity_tolerance;
	if("POSITION_TOLERANCE"==name) return &ARMCastToPosition_tolerance;
	if("RADIAL_SIZE_DIMENSION"==name) return &ARMCastToRadial_size_dimension;
	if("ROUNDNESS_TOLERANCE"==name) return &ARMCastToRoundness_tolerance;
	if("STRAIGHTNESS_TOLERANCE"==name) return &ARMCastToStraightness_tolerance;
	if("SURFACE_PROFILE_TOLERANCE"==name) return &ARMCastToSurface_profile_tolerance;
	if("SYMMETRY_TOLERANCE"==name) return &ARMCastToSymmetry_tolerance;
	if("TARGET_CIRCLE"==name) return &ARMCastToTarget_circle;
	if("TARGET_POINT"==name) return &ARMCastToTarget_point;
	if("TARGET_RECTANGLE"==name) return &ARMCastToTarget_rectangle;
	if("TARGET_STRAIGHT_LINE"==name) return &ARMCastToTarget_straight_line;
	if("TARGET_AREA"==name) return &ARMCastToTarget_area;
	if("THICKNESS_SIZE_DIMENSION"==name) return &ARMCastToThickness_size_dimension;
	if("TOLERANCE_PLUS_MINUS_VALUE"==name) return &ARMCastToTolerance_plus_minus_value;
	if("TOLERANCE_ZONE"==name) return &ARMCastToTolerance_zone;
	if("TOTAL_RUNOUT_TOLERANCE"==name) return &ARMCastToTotal_runout_tolerance;
	if("WIDTH_SIZE_DIMENSION"==name) return &ARMCastToWidth_size_dimension;
	if("STYLED_DRAUGHTING_MODEL"==name) return &ARMCastToStyled_draughting_model;
	if("STYLED_GEOMETRIC_MODEL"==name) return &ARMCastToStyled_geometric_model;
	if("STYLED_SHADED_MODEL"==name) return &ARMCastToStyled_shaded_model;
	if("DRAUGHTING_CALLOUT_ITEM"==name) return &ARMCastToDraughting_callout_item;
	if("SINGLE_STYLED_ITEM"==name) return &ARMCastToSingle_styled_item;
	if("COMPOSITE_CALLOUT"==name) return &ARMCastToComposite_callout;
	if("CALLOUT"==name) return &ARMCastToCallout;
	if("PROPERTY"==name) return &ARMCastToProperty;
	return nullptr;
};